name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet publish --runtime linux-x64 -p:PublishReadyToRun=true -v n
    
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-dotnet@v1
    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: ""
        SOURCE: "dist/"
        REMOTE_HOST: ${{ secrets.SSH_REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.SSH_REMOTE_USER }}
        TARGET: ${{ secrets.SSH_TARGET }}
    - name:  Print stuff
      run: echo "All done!"
    
      
